### ISSUE TITLE
Unable to see any captures

### ISSUE THREAD

**Issue by ZoguBK** [GameTechDev/UE4_GPA_Plugin#1]
I'm using UE_4.26.2.
Download includes only source files so I added the plugin to project plugins folder. Compiled and enabled the plugin.
In UE Editor when I click on GPA Captures it starts and clicking it again it stops captures. 
Notifications are shown in the bottom right corner. 
After capturing is stopped Graphic Monitor is opened. But I cant see captures from my project.
![GPA Monitor](https://user-images.githubusercontent.com/36535809/133452443-f34f47a2-42a7-4bf4-84ce-6c7a0d696618.png)

What am I missing?

**Comment by rmkawiak** [comment]
Hi @ZoguBK, can you download the latest version of this plugin and give it a try? I made changes in the plugin to make sure there are no compatibility issues

**Comment by ZoguBK** [comment]
With the latest version it is working as intended.
