### ISSUE TITLE
Wrong third party library path

### ISSUE THREAD

**Issue by Settius** [GameTechDev/UE4_GPA_Plugin#4]
Plugin module is not loaded properly (tested on latest version of GPA). There is issue with wrong path to igpa-shim-loader-x64.dll (no such file in GPA folder).

I'm using UE 4.26.2.

**Comment by rmkawiak** [comment]
Hi @Settius, could you check if you have the GPA Framework installed (it is needed in addition to Graphics Performance Analyzers), here's the direct link:
[https://registrationcenter-download.intel.com/akdlm/irc_nas/18161/intel-gpa-framework-21.3.msi](https://registrationcenter-download.intel.com/akdlm/irc_nas/18161/intel-gpa-framework-21.3.msi)

If you used the install defaults, it should be located in:
C:\Program Files\IntelSWTools\GPA Framework\21.3

**Comment by Settius** [comment]
Thanks, it works now.
