### ISSUE TITLE
GPA capture icon is invisible when "use small tool bar icons" is enabled

### ISSUE THREAD

**Issue by adam-wolski** [GameTechDev/UE4_GPA_Plugin#5]
With "use small tool bar icons" enabled in editor preferences GPA capture icon is invisible.

![image](https://user-images.githubusercontent.com/6629924/134773183-81216442-d60b-4b92-aa73-95b622f66435.png)

**Comment by rmkawiak** [comment]
Hi Adam, thanks for finding this problem. It has been fixed with [this commit](https://github.com/GameTechDev/UE4_GPA_Plugin/pull/6)

**Comment by adam-wolski** [comment]
Thank you, that fixed it :)
